#!/usr/bin/env python3

import sys
import robust_layer.git

if len(sys.argv) < 2:
    raise Exception("not enough parameters")

if sys.argv[1] == "clone":
    robust_layer.git.clone(sys.argv[2:])
    sys.exit(0)

if sys.argv[1] == "fetch":
    robust_layer.git.fetch(sys.argv[2:])
    sys.exit(0)

if sys.argv[1] == "pull":
    robust_layer.git.pull(sys.argv[2:])
    sys.exit(0)

if sys.argv[1] == "push":
    robust_layer.git.push(sys.argv[2:])
    sys.exit(0)

raise Exception("operation \"%s\" not supported" % (sys.argv[1]))
